Repository opt-nc/mobitag, pull requests merged in 2025-02, with the labels that each got.

#2 feat: ajout du goreleaser
  .github/workflows/go.yml
  .github/workflows/goreleaser.yml
  .gitignore
  .goreleaser.yaml
Labels: BUILD, enhancement, quickfix

#3 Develop
  .github/workflows/go.yml
  .github/workflows/goreleaser.yml
  .gitignore
  .goreleaser.yaml
Labels: BUILD, enhancement, quickfix

#11 feat: support du pipe pour envoyer un message et des workflowq
  .github/dependabot.yml
  .github/workflows/goreleaser.yml
  .github/workflows/test-release.yml
  .goreleaser.yaml
  Taskfile.yml
  cmd/send.go
  cmd/sendPipe.go
Labels: BUILD

#17 16 choisir la licence adaptée
  .github/dependabot.yml
  .github/workflows/goreleaser.yml
  .github/workflows/test-release.yml
  .goreleaser.yaml
  LICENSE
  Taskfile.yml
  cmd/send.go
  cmd/sendPipe.go
Labels: BUILD, documentation, quickfix

#25 Supervinh patch
  .github/workflows/golangci-lint.yml
  .github/workflows/goreleaser.yml
  .github/workflows/test-release.yml
  .releaserc
  cmd/about.go
  cmd/send.go
  cmd/sendPipe.go
  go.mod
Labels: BUILD

#27 fix: fix of the release workflow
  .github/workflows/test-release.yml
Labels: BUILD, bug, quickfix

#28 Develop
  .github/workflows/golangci-lint.yml
  .github/workflows/goreleaser.yml
  .github/workflows/test-release.yml
  .releaserc
  cmd/about.go
  cmd/send.go
  cmd/sendPipe.go
  go.mod
  go.sum
Labels: BUILD

#29 feat: ajout de l'option cut et du github token
  .github/workflows/test-release.yml
  cmd/send.go
  cmd/sendPipe.go
Labels: BUILD, enhancement

#30 Develop
  .github/workflows/test-release.yml
  cmd/send.go
  cmd/sendPipe.go
  go.mod
  go.sum
Labels: BUILD, enhancement

#31 fix: GITHUB_TOKEN
  .github/workflows/test-release.yml
  .releaserc.json
Labels: bug

#32 fix: goreleaser
  .github/workflows/goreleaser.yml
  .releaserc.json
Labels: bug

#33 fix: ajout du goreleaser à test-release.yml
  .github/workflows/goreleaser.yml
  .github/workflows/test-release.yml
  .releaserc.json
Labels: bug

#34 Develop
  .github/workflows/goreleaser.yml
  .github/workflows/test-release.yml
  .releaserc
  .releaserc.json
Labels: BUILD, bug

#45 Supervinh patch
  .goreleaser.yaml
  HOWTOBUILD.md
  README.md
  cmd/about.go
  cmd/dryRun.go
  cmd/root.go
  cmd/send.go
  cmd/sendPipe.go
  cmd/version.go
  main.go
  mobitag.tape
Labels: BUILD, documentation

#46 Develop
  .goreleaser.yaml
  HOWTOBUILD.md
  README.md
  cmd/about.go
  cmd/dryRun.go
  cmd/root.go
  cmd/send.go
  cmd/sendPipe.go
  cmd/version.go
  main.go
  mobitag.tape
Labels: BUILD, documentation, released on @develop
