Repository opt-nc/mobitag, pull requests merged in 2025-04, with the labels that each got.

#122 :sponge: `mobtag-cli` apparaît dans la demo vhs
  mobitag-auth.tape
  mobitag-no-auth.tape
Labels: RUN, bug, documentation, quickfix

#124 Ajout de la commande web et différents fix
  .github/workflows/test-release.yml
  cmd/about.go
  cmd/dryRun.go
  cmd/pipe.go
  cmd/send.go
  cmd/web.go
  go.mod
  go.sum
Labels: BUILD, enhancement

#125 Develop
  .github/workflows/test-release.yml
  cmd/about.go
  cmd/dryRun.go
  cmd/pipe.go
  cmd/send.go
  cmd/web.go
  go.mod
  go.sum
  media/auth/mobitag.gif
  media/auth/mobitag.webm
  mobitag-auth.tape
  mobitag-no-auth.tape
Labels: BUILD, enhancement

#130 :name_badge: Ajout shield de lint
  README.md
Labels: BUILD, documentation, quickfix

#127 :gun: Oneliner > Envoi en masse avec un `csv` d'input et `awk`
  README.md
Labels: BUILD, documentation, quickfix, succes-remarquable, one-liner
