Repository opt-nc/mobitag, pull requests merged in 2025-09, with the labels that each got.

#167 fix: Enlever le from tant que from ne fonctionne pas
  cmd/root.go
Labels: RUN, bug, quickfix

#172 🗝️ Create and send passwords by sms with a "burn after reading"
  README.md
Labels: BUILD, documentation, enhancement, quickfix, succes-remarquable, security, one-liner, communication

#176 Supervinh patch
  .github/dependabot.yml
  .github/workflows/golangci-lint.yml
  .github/workflows/test-release.yml
  Taskfile.yml
  cmd/pipe.go
  cmd/send.go
  go.mod
Labels: RUN, quickfix

#179 fix: vhs and curl go report card
  .github/workflows/test-release.yml
  README.md
  mobitag-auth.tape
Labels: RUN, documentation, quickfix

#180 Develop
  .github/workflows/test-release.yml
  README.md
  media/auth/mobitag.gif
  media/auth/mobitag.webm
  mobitag-auth.tape
Labels: RUN, documentation, quickfix
