Repository opt-nc/mobitag, pull requests merged in 2025-03, with the labels that each got.

#51 Supervinh patch 1
  .github/workflows/test-release.yml
  .gitignore
  HOWTOBUILD.md
  README.md
  Taskfile.yml
  cmd/send.go
  cmd/sendPipe.go
  media/README.md
  media/auth/mobitag.webm
  media/mobitag-cli.gif
  media/mobitag-cli.mp4
  media/mobitag-cli.webm
  mobitag-auth.tape
  mobitag-no-auth.tape
Labels: BUILD, enhancement

#52 fix: mise à jour de la version de la vhs-action
  .github/workflows/test-release.yml
Labels: quickfix

#53 fix: pas de build automatique de la vhs pour le moment
  .github/workflows/test-release.yml
Labels: quickfix

#55 Develop
  .github/workflows/test-release.yml
  .gitignore
  HOWTOBUILD.md
  README.md
  Taskfile.yml
  cmd/send.go
  cmd/sendPipe.go
  media/README.md
  media/auth/mobitag.webm
  media/mobitag-cli.gif
  media/mobitag-cli.mp4
  media/mobitag-cli.webm
  mobitag-auth.tape
  mobitag-no-auth.tape
Labels: BUILD, enhancement

#57 :people_holding_hands:README : section team players :raised_hands:
  README.md
Labels: BUILD, documentation, quickfix

#60 :magic_wand: Ajouter un exemple pour l'opérateur `|` et section "OneLiners"
  README.md
  cmd/sendPipe.go
Labels: BUILD, documentation, quickfix, succes-remarquable

#62 📖 Adress book : Ajout d'un Taskfile pour gérer des alias :test_tube:
  contribs/Taskfile.yml
Labels: BUILD, enhancement

#63 doc: rajout de la vhs en .gif pour le README
  README.md
  media/auth/mobitag.gif
  media/auth/mobitag.webm
  mobitag-auth.tape
Labels: documentation

#64 fix: suppression de l'emoji
  cmd/about.go
Labels: quickfix

#65 Develop
  README.md
  cmd/about.go
  cmd/sendPipe.go
  contribs/Taskfile.yml
  media/auth/mobitag.gif
  media/auth/mobitag.webm
  mobitag-auth.tape
Labels: documentation, quickfix

#66 feat: ajout du build de brew avec goreleaser
  .goreleaser.yaml
Labels: BUILD, enhancement

#67 fix: utilisation du nouveau PAT
  .goreleaser.yaml
Labels: BUILD, quickfix

#68 fix: ajout du token dans l'environnement
  .github/workflows/test-release.yml
Labels: BUILD, quickfix

#69 Develop
  .github/workflows/test-release.yml
  .goreleaser.yaml
Labels: BUILD, quickfix

#70 Supervinh patch 1
  .releaserc.json
  README.md
Labels: BUILD, documentation, quickfix

#71 feat: ajout du checksums.txt et des sboms
  .github/workflows/test-release.yml
  .goreleaser.yaml
Labels: BUILD, enhancement

#72 fix: github workflow
  .github/workflows/test-release.yml
Labels: BUILD, quickfix

#73 fix: update du workflow github
  .github/workflows/golangci-lint.yml
  .github/workflows/test-release.yml
Labels: BUILD

#74 fix: workflow
  .goreleaser.yaml
  .releaserc.json
Labels: BUILD

#75 Develop
  .github/workflows/golangci-lint.yml
  .github/workflows/test-release.yml
  .goreleaser.yaml
  .releaserc.json
  README.md
Labels: BUILD, enhancement

#78 :memo: Installer et mettre à jour avec `brew` :beer:
  README.md
Labels: BUILD, documentation, quickfix

#80 :sloth: doc : Simplification scénario install brew
  README.md
Labels: BUILD, documentation, enhancement, quickfix

#86 Supervinh patch 1
  .github/workflows/test-release.yml
  .goreleaser.yaml
  cmd/about.go
  go.mod
  go.sum
  media/auth/mobitag.gif
  media/auth/mobitag.webm
Labels: BUILD, github_actions

#89 fix: github workflow pour générer la vhs
  .github/workflows/test-release.yml
Labels: quickfix, github_actions

#90 fix: github workflow
  .github/workflows/test-release.yml
Labels: quickfix, github_actions

#91 fix: github workflow
  .github/workflows/test-release.yml
Labels: quickfix, github_actions

#92 feat: commit du .webm et modification du tape vhs
  .github/workflows/test-release.yml
  mobitag-auth.tape
Labels: quickfix, github_actions

#93 feat: modification du github workflow pour push les vhs générés
  .github/workflows/test-release.yml
  .goreleaser.yaml
  cmd/about.go
Labels: github_actions

#94 feat: modification du vhs et export des secrets
  .github/workflows/test-release.yml
  mobitag-auth.tape
Labels: quickfix, github_actions

#97 83 documenter processus buildinstall go
  .goreleaser.yaml
  README.md
  go.mod
  main.go
  mobitag-auth.tape
Labels: BUILD, documentation

#99 Supervinh patch 1
  .goreleaser.yaml
  HOWTOBUILD.md
  README.md
  go.mod
  main.go
  mobitag-auth.tape
Labels: BUILD, documentation, quickfix

#100 Develop
  .github/workflows/golangci-lint.yml
  .github/workflows/test-release.yml
  .goreleaser.yaml
  HOWTOBUILD.md
  README.md
  cmd/about.go
  go.mod
  go.sum
  main.go
  media/auth/mobitag.gif
  media/auth/mobitag.webm
  mobitag-auth.tape
Labels: BUILD, documentation, enhancement, github_actions

#102 :memo: documenter comment désinstaller mobitag avec brew
  README.md
Labels: BUILD, documentation, enhancement, quickfix

#109 :people_holding_hands: implémeter le code of conductmd
  CODE_OF_CONDUCT.md
  README.md
Labels: BUILD, documentation, quickfix

#114 Supervinh patch 1
  .github/workflows/golangci-lint.yml
  .goreleaser.yaml
  README.md
  cmd/about.go
  cmd/root.go
  cmd/send.go
  cmd/sendPipe.go
  mobitag-auth.tape
Labels: BUILD, github_actions

#115 Develop
  .github/workflows/golangci-lint.yml
  .goreleaser.yaml
  CODE_OF_CONDUCT.md
  README.md
  cmd/about.go
  cmd/root.go
  cmd/send.go
  cmd/sendPipe.go
  media/auth/mobitag.gif
  media/auth/mobitag.webm
  mobitag-auth.tape
Labels: BUILD, github_actions
